[package]
name = "tee-login"
version = "0.1.0"
edition = "2024"

[dependencies]
hex = "0.4"
tokio = "1.45.1"
fastcrypto = { git = "https://github.com/MystenLabs/fastcrypto", rev = "69d496c71fb37e3d22fe85e5bbfd4256d61422b9", features = ["aes","copy_key"] }
shared_crypto = { git = "https://github.com/mystenlabs/sui", rev = "574e17b5ef3b96146aebcd23f3e8b1d20b14e6ae", package = "shared-crypto"}
mina-signer = { git = "https://github.com/o1-labs/proof-systems", branch = "master", package = "mina-signer" }
bcs = "0.1.4"
rocket = { version = "0.5.1", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0.98"
base64 = "0.22.1"
rsa = "0.9.8"
sha2 = "0.10.9"
bip39 = { version = "2", features = ["zeroize", "rand", "std"] }
rand = "0.8.5"
zeroize = "1.8.1"
rocksdb = { version = "^0.22.0", features = ["lz4"] } 
bincode = "1.3"
chrono = { version = "0.4.41", features = ["serde"] }
log = "0.4"
env_logger = "0.11"
serde_json = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
tracing-appender = "0.2"
bc-shamir = "0.8.0"
bc-rand = "0.4.0"
aws-sdk-dynamodb = "1.80.0"
aws-sdk-kms = "1.76.0"
aws-config = "1.8.0"
aes-gcm = "0.10"
dotenvy = "0.15.7"
ed25519-dalek = "2.1"
bs58 = "0.5.0"
ethers-core = "2.0.14"
secp256k1  = { version = "0.30", features = ["recovery"] }
jsonwebtoken = "9.3.1"
once_cell = "1.21.3"
reqwest = { version = "0.12.20", features = ["json"] }

