[package]
name = "tee-login"
version = "0.1.0"
edition = "2024"

[dependencies]
solana-sdk = "2.3"
hex = "0.4"
tokio = "1.45.1"
sui_sdk = { git = "https://github.com/mystenlabs/sui", package = "sui-sdk"}
rocket = { version = "0.5.1", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0.98"
base64 = "0.22.1"
rsa = "0.9.8"
sha2 = "0.10.9"
bip39 = { version = "2", features = ["zeroize", "rand", "std"] }
rand = "0.9.1"
zeroize = "1.8.1"
rocksdb = { version = "^0.22.0", features = ["lz4"] } 
bincode = "1.3"
chrono  = "0.4"
log = "0.4"
env_logger = "0.11"
serde_json = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
tracing-appender = "0.2"
bc-shamir = "0.8.0"
bc-rand = "0.4.0"
aws-sdk-dynamodb = "1.80.0"
aws-sdk-kms = "1.76.0"
aws-config = "1.8.0"
aes-gcm = "0.10"
dotenvy = "0.15.7"
