[package]
name = "hash"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
chrono = "0.4"
clap = { version = "4", features = ["derive"] }
dotenvy = "0.15"
hex = "0.4"
reqwest = { version = "0.12", features = ["json", "rustls-tls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10.9"
tiny-keccak = { version = "2.0", features = ["keccak"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
indexed-merkle-map = { git = "https://github.com/SilvanaOne/silvana.git", package = "indexed-merkle-map" }
crypto-bigint = "=0.5.5"
tonic = { version = "0.12", features = ["tls", "tls-webpki-roots"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1.0", features = ["v4"] }
