[package]
name = "forwarder"
version = "0.1.0"
edition = "2024"
authors = ["DFST"]
license = "Apache-2.0"


[dependencies]
libc = "0.2"
log = "0.4"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
