[package]
name = "sea"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio     = { version = "1", features = ["macros", "rt-multi-thread"] }
rand      = "0.8"
dotenvy   = "0.15"

sea-orm   = { version = "1.1.12", features = [
    "sqlx-mysql",
    "runtime-tokio-native-tls",
    "macros"        # derive EntityModel/ActiveModel
] }
anyhow = "1.0.98"
