[package]
name = "lambda-minimum"
version = "0.1.0"
edition = "2024"

[dependencies]

lambda_runtime = "0.14.2"
serde = "1"
tokio = { version = "1", features = ["macros"] }
sui_sdk = { git = "https://github.com/mystenlabs/sui", package = "sui-sdk" }
anyhow = "1.0"
