[workspace]
resolver = "2"
members = [
    "crates/api",
    "crates/api-generated",
    "crates/db",
    "crates/kms", 
    "crates/lambda",
    "crates/sui",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["DFST"]
license = "Apache-2.0"

[workspace.dependencies]
