[package]
name = "rpc"
version = "0.1.0"
edition = "2021"
authors = ["DFST"]
license = "Apache-2.0"
default-run = "rpc"

[dependencies]
tonic = { version = "0.10", features = ["tls", "tls-webpki-roots"] }
tonic-web = "0.10"
prost = "0.12"
prost-types = "0.12"
tokio = { version = "1.45", features = ["macros", "rt-multi-thread", "time"] }
tokio-stream = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tower-http = { version = "0.4", features = ["cors"] }

# Monitoring dependencies
prometheus = "0.14"
axum = "0.7"
# OpenTelemetry
opentelemetry = "0.21"
opentelemetry_sdk = "0.21"
opentelemetry-otlp = "0.14"
tracing-opentelemetry = "0.22"

# Sea-ORM and Database
sea-orm = { version = "1.1", features = ["sqlx-mysql", "runtime-tokio-rustls", "macros", "with-chrono", "with-json", "with-uuid"] }
sea-orm-migration = "1.1"
sqlx = { version = "0.8", features = ["mysql", "runtime-tokio-rustls", "chrono", "uuid"] }

# Time and UUID
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.17", features = ["v4", "serde"] }

# Environment and Config
dotenvy = "0.15"
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-appender = "0.2"

# NATS (placeholder for future implementation)
async-nats = "0.36"

# Async utilities
futures = "0.3"
async-trait = "0.1"

# Random number generation for retry jitter
fastrand = "2.0"

[dev-dependencies]
# For integration tests
tokio-test = "0.4"

[build-dependencies]
tonic-build = "0.10"
prost-build = "0.12"
# For custom code generation
syn = { version = "2.0", features = ["full", "parsing"] }
quote = "1.0"
proc-macro2 = "1.0"
prettyplease = "0.2"
