[package]
name = "billing"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
base64 = "0.22"
bincode = "1.3"
chrono = "0.4"
clap = { version = "4", features = ["derive", "env"] }
dotenvy = "0.15"
opentelemetry = { version = "0.27", features = ["trace", "metrics", "logs"] }
opentelemetry-otlp = { version = "0.27", features = ["logs", "metrics", "trace", "grpc-tonic", "http-proto", "tls"] }
opentelemetry_sdk = { version = "0.27", features = ["rt-tokio", "logs", "metrics", "trace"] }
prometheus = { version = "0.13", features = ["process"] }
regex = "1"
reqwest = { version = "0.12", features = ["json", "rustls-tls"] }
rocksdb = { version = "^0.22.0", features = ["lz4"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
time = { version = "0.3", features = ["formatting", "macros"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
tonic = { version = "0.12", features = ["tls", "tls-webpki-roots"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "time", "local-time"] }
