[package]
name = "aggregate"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "2.0.1", features = [
  "std",
], default-features = false }
balance-methods = { path = "../../../balance/methods" }
balance-core = { path = "../../../balance/core" }
