[package]
name = "ika"
version = "0.1.0"
edition = "2024"

[dependencies]
ika_sdk = { git = "https://github.com/dwallet-labs/dwallet-network", package = "ika-sdk"}
tokio = { version = "1.2", features = ["full"] }
anyhow = "1.0"