[package]
name = "bcs-client"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15.7"
tokio = { version = "1.2", features = ["full"] }
fastcrypto = { git = "https://github.com/MystenLabs/fastcrypto", features = ["aes","copy_key"] }
shared_crypto = { git = "https://github.com/mystenlabs/sui", package = "shared-crypto"}
sui_sdk = { git = "https://github.com/mystenlabs/sui", package = "sui-sdk" }
sui_keys = { git = "https://github.com/mystenlabs/sui", package = "sui-keys" }
anyhow = "1.0"
bcs = "0.1"
futures = "0.3.31"
move-core-types = { git = "https://github.com/mystenlabs/sui", package = "move-core-types" }
serde = { version = "1.0", features = ["derive"] }
hex = "0.4"