[package]
name = "signer"
version = "0.1.0"
edition = "2024"



[dependencies]
mina-hasher = { git = "https://github.com/o1-labs/proof-systems", branch = "master", package = "mina-hasher" }
mina-signer = { git = "https://github.com/o1-labs/proof-systems", branch = "master", package = "mina-signer" }
rand_core = { version = "0.6.3" }
