[package]
version = "0.1.0"
name = "add-program"
edition = "2021"

[dependencies]
alloy-sol-types = { workspace = true }
sp1-zkvm = "5.1.0"
add-lib = { path = "../../lib/add" }
indexed-merkle-map = { path = "../../../../rust/indexed-merkle-map", default-features = false }
borsh = { version = "1.5", default-features = false, features = ["derive"] }
