[package]
name = "jwt"
version = "0.1.0"
edition = "2024"

[dependencies]
jsonwebtoken = "9.3"
ed25519-dalek = { version = "2.1", features = ["rand_core"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
base64 = "0.22"
rand = "0.8"
