# .cargo/config.toml
[build]
jobs = 16                 # match vCPU count
rustflags = [
  "-Ctarget-cpu=native",
  "-Ccodegen-units=16",
  "-Ctarget-feature=+crt-static",
  "-Crelocation-model=static"
]

[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor/"