[package]
name = "precompiles"
version = "0.1.0"
edition = "2024"

[lib]                   
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = { version = "0.2", features = ["serde", "serde_json", "spans", "enable-interning"] }
zeroize = "1.8.1"
bip39 = { version = "2", features = ["zeroize", "std"] }
bc-shamir = "0.8.0"
getrandom = { version = "0.2", features = ["js"] }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
js-sys = "0.3.77"
web-sys = { version = "0.3.77", features = ["console"] }
mina-hasher = { git = "https://github.com/o1-labs/proof-systems", branch = "master", package = "mina-hasher" }
mina-signer = { git = "https://github.com/o1-labs/proof-systems", branch = "master", package = "mina-signer" }
rand_core = { version = "0.6.3" }
ciborium = "0.2.2"
hex = "0.4.3"
once_cell = "1.21.3"
p384 = "0.13.1"
rustls-pemfile = "2.2.0"
serde_json = "1.0.133"
x509-parser = { version = "0.17.0", features = ["verify"] }

