[package]
name = "controller"
version = "0.1.0"
edition = "2024"



[dependencies]
bollard = "0.19"
tokio = { version = "1.2", features = ["full"] }
futures-util = "0.3"
chrono = "0.4"
bytes = "1"
dotenv = "0.15.0"
fastcrypto = { git = "https://github.com/MystenLabs/fastcrypto", features = ["aes","copy_key"] }
shared_crypto = { git = "https://github.com/mystenlabs/sui", package = "shared-crypto"}
sui_sdk = { git = "https://github.com/mystenlabs/sui", package = "sui-sdk" }
sui_keys = { git = "https://github.com/mystenlabs/sui", package = "sui-keys" }
anyhow = "1.0"
reqwest = "0.12.19"
serde = "1.0.219"
serde_json = "1.0"
hex = "0.4"
bcs = "0.1"
futures = "0.3.31"
parking_lot = "0.12.4"
http = "1.3.1"
