version = 3

root  = "/var/lib/containerd"
state = "/run/containerd"


[grpc]
  # If you're forwarding vsock ↔ TCP from the host into the enclave,
  # point containerd's gRPC listener at the vsock address; otherwise keep default.
  # address = "vsock://3:10250"
  address = "/run/containerd/containerd.sock"
  uid = 0
  gid = 0

[debug]
  level = "debug"

[plugins."io.containerd.cri.v1.images"."docker.io"]
  config_path = "/etc/containerd/certs.d"

[plugins."io.containerd.cri.v1.images"."registry-1.docker.io"]
  config_path = "/etc/containerd/certs.d"
