[package]
name = "grpc"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic = { version = "0.13", features = ["tls-webpki-roots"] }
tonic-reflection = "0.13"
prost = "0.13"
prost-types = "0.13"
prost-reflect = { version = "0.15.3", features = ["derive"] }
prost-reflect-build = "0.15.2"
once_cell = "1.21.3"

# Additional dependencies for our REST events functionality
tokio = { version = "1.0", features = ["macros", "rt-multi-thread", "fs"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.12", features = ["json"] }
hex = "0.4"
rustls = { version = "0.23", features = ["ring"] }
chrono = { version = "0.4", features = ["serde"] }

[build-dependencies]
tonic = { version = "0.13", features = ["tls-webpki-roots"] }
tonic-reflection = "0.13"
tonic-build = "0.13"
prost-build = "0.13"
prost-reflect = { version = "0.15.3", features = ["derive"] }
prost-reflect-build = "0.15.2"
once_cell = "1.21.3"
