[package]
name = "db"
version.workspace = true
edition.workspace = true

[dependencies]
aws-config = "1.8"
aws-sdk-dynamodb = "1.89"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1.0"
tracing = "0.1"
chrono = "0.4"
bincode = "1.3"
kms = { path = "../kms" }
