[package]
version = "0.1.0"
name = "mina-program"
edition = "2024"

[lib]
name = "mina_lib"
path = "src/lib.rs"

[[bin]]
name = "mina-program"
path = "src/main.rs"

[dependencies]
sp1-zkvm = { version = "5.1.0" }
num-bigint = { version = "0.4", default-features = false }
once_cell = "1.19"