[package]
name = "generate"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "exp"
path = "src/exp.rs"

[dependencies]
bls12_381 = "0.8.0"
ff = "0.13.1"
rand = "0.8"
hex = "0.4"
num-bigint = "0.4"
num-traits = "0.2"

