[package]
name = "p2p"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio      = { version = "1.38", features = ["full"] }
tonic      = "0.11"         # gRPC over HTTP/2 ➜ TCP
tonic-reflection = "0.11"   # gRPC reflection for easier testing
tonic-web  = "0.11"         # gRPC-Web support
prost      = "0.12"         # Protobuf (auto pulled by tonic)
serde      = { version = "1.0", features = ["derive"] }
serde_json = "1.0"          # JSON serialization
axum       = "0.7"          # REST API framework
tower      = "0.4"          # Service abstractions
tower-http = { version = "0.5", features = ["cors", "trace"] }
anyhow = "1.0.98"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
rand = "0.8"                # For generating random data in tests
base64 = "0.22"             # For encoding bytes in JSON

[build-dependencies]
tonic-build = "0.11"        # code-gen for *.proto
