[package]
name = "indexed-merkle-map"
version = "0.1.0"
edition = "2024"
authors = ["DFST"]
license = "Apache-2.0"

[dependencies]
crypto-bigint = "=0.5.5"
sha2 = "=0.10.9"
borsh = { version = "1.5", features = ["derive"] }

[features]
default = ["std"]
std = []
# Enable this feature when compiling for zkVM to hide non-provable code
zkvm = []

[dev-dependencies]
rand = "0.9.2"
