[package]
name = "indexed-merkle-map"
version = "0.1.0"
edition = "2024"
authors = ["DFST"]

[dependencies]
crypto-bigint = "=0.5.5"
sha2 = "=0.10.9"
borsh = { version = "1.5", features = ["derive"] }
