[package]
version = "0.1.0"
name = "aggregate-program"
edition = "2024"

[dependencies]
alloy-sol-types = { workspace = true }
sp1-zkvm = { version = "5.1.0", features = ["verify"] }
add-lib = { path = "../../lib/add" }
sha2 = "=0.10.9"
