[package]
version = "0.1.0"
name = "aggregate-program"
edition = "2021"

[dependencies]
alloy-sol-types = { workspace = true }
sp1-zkvm = { version = "5.1.0", features = ["verify"] }
add-lib = { path = "../../lib/add" }
sha2 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", package = "sha2", tag = "sha2-v0.10.8-patch-v1" }
