[workspace]
members = [
    "lib",
    "sui/client",
    "programs/add",
    "programs/aggregate",
    "programs/sha256",
    "programs/p3",
    "programs/mina",
    "script",
]
resolver = "2"

[workspace.dependencies]
alloy-sol-types = "1.3"
