[workspace]
members = [
    "lib/add",
    # "lib/proof", # Temporarily excluded due to serde version conflict with mina-hasher
    "sui/client",
    "programs/add",
    "programs/aggregate",
    "programs/sha256",
    "programs/p3",
    # "programs/ps", # Temporarily excluded due to serde version conflict
    "programs/mina",
    # "programs/proof", # Depends on proof-lib
    # "script", # Depends on proof-lib
    "witness",
]

exclude = ["arbitrum"]

default-members = [
    "lib/add",
    # "lib/proof", # Temporarily excluded
    "sui/client",
    # "script", # Temporarily excluded
    "witness",
]

resolver = "2"

[workspace.dependencies]
alloy-sol-types = "1.3"

[patch.crates-io]
crypto-bigint = { git = "https://github.com/sp1-patches/RustCrypto-bigint", tag = "patch-0.5.5-sp1-4.0.0" }
sha2 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", package = "sha2", tag = "patch-sha2-0.10.9-sp1-4.0.0" }
