/*
 * Advanced Payment Devnet API
 *
 * REST API for Canton Network Advanced Payment operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdvancedPaymentRequestInfo {
    #[serde(rename = "contract_id")]
    pub contract_id: String,
    #[serde(rename = "locked_amount")]
    pub locked_amount: String,
    #[serde(rename = "minimum_amount")]
    pub minimum_amount: String,
    #[serde(rename = "buyer")]
    pub buyer: String,
    #[serde(rename = "seller")]
    pub seller: String,
    #[serde(rename = "provider")]
    pub provider: String,
    #[serde(rename = "expires_at")]
    pub expires_at: String,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "reference", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub reference: Option<Option<String>>,
}

impl AdvancedPaymentRequestInfo {
    pub fn new(contract_id: String, locked_amount: String, minimum_amount: String, buyer: String, seller: String, provider: String, expires_at: String) -> AdvancedPaymentRequestInfo {
        AdvancedPaymentRequestInfo {
            contract_id,
            locked_amount,
            minimum_amount,
            buyer,
            seller,
            provider,
            expires_at,
            description: None,
            reference: None,
        }
    }
}

