/*
 * Advanced Payment Devnet API
 *
 * REST API for Canton Network Advanced Payment operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AmuletInfo {
    #[serde(rename = "contract_id")]
    pub contract_id: String,
    #[serde(rename = "amount")]
    pub amount: String,
    #[serde(rename = "is_locked")]
    pub is_locked: bool,
    #[serde(rename = "lock_holders")]
    pub lock_holders: Vec<String>,
    #[serde(rename = "lock_expires_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub lock_expires_at: Option<Option<String>>,
}

impl AmuletInfo {
    pub fn new(contract_id: String, amount: String, is_locked: bool, lock_holders: Vec<String>) -> AmuletInfo {
        AmuletInfo {
            contract_id,
            amount,
            is_locked,
            lock_holders,
            lock_expires_at: None,
        }
    }
}

