/*
 * Advanced Payment Devnet API
 *
 * REST API for Canton Network Advanced Payment operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppServiceInfo {
    #[serde(rename = "contract_id")]
    pub contract_id: String,
    #[serde(rename = "seller")]
    pub seller: String,
    #[serde(rename = "provider")]
    pub provider: String,
    #[serde(rename = "service_description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub service_description: Option<Option<String>>,
}

impl AppServiceInfo {
    pub fn new(contract_id: String, seller: String, provider: String) -> AppServiceInfo {
        AppServiceInfo {
            contract_id,
            seller,
            provider,
            service_description: None,
        }
    }
}

