/*
 * Advanced Payment Devnet API
 *
 * REST API for Canton Network Advanced Payment operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BuyerCredentials : buyer_party_id and buyer_private_key required; jwt falls back to .env
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BuyerCredentials {
    /// JWT for Ledger API authentication
    #[serde(rename = "jwt", skip_serializing_if = "Option::is_none")]
    pub jwt: Option<String>,
    /// Buyer party ID
    #[serde(rename = "buyer_party_id")]
    pub buyer_party_id: String,
    /// Base58-encoded Ed25519 private key
    #[serde(rename = "buyer_private_key")]
    pub buyer_private_key: String,
}

impl BuyerCredentials {
    /// buyer_party_id and buyer_private_key required; jwt falls back to .env
    pub fn new(buyer_party_id: String, buyer_private_key: String) -> BuyerCredentials {
        BuyerCredentials {
            jwt: None,
            buyer_party_id,
            buyer_private_key,
        }
    }
}

