/*
 * Advanced Payment Devnet API
 *
 * REST API for Canton Network Advanced Payment operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HealthResponse {
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "ledger_api_url")]
    pub ledger_api_url: String,
    #[serde(rename = "scan_api_url")]
    pub scan_api_url: String,
}

impl HealthResponse {
    pub fn new(status: String, ledger_api_url: String, scan_api_url: String) -> HealthResponse {
        HealthResponse {
            status,
            ledger_api_url,
            scan_api_url,
        }
    }
}

