/*
 * Advanced Payment Devnet API
 *
 * REST API for Canton Network Advanced Payment operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListAmuletsRequest {
    #[serde(rename = "jwt", skip_serializing_if = "Option::is_none")]
    pub jwt: Option<String>,
    /// Party to list amulets for
    #[serde(rename = "party_id")]
    pub party_id: String,
}

impl ListAmuletsRequest {
    pub fn new(party_id: String) -> ListAmuletsRequest {
        ListAmuletsRequest {
            jwt: None,
            party_id,
        }
    }
}

