/*
 * Advanced Payment Devnet API
 *
 * REST API for Canton Network Advanced Payment operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaymentTopupRequest {
    /// JWT for Ledger API authentication
    #[serde(rename = "jwt", skip_serializing_if = "Option::is_none")]
    pub jwt: Option<String>,
    /// Buyer party ID
    #[serde(rename = "buyer_party_id")]
    pub buyer_party_id: String,
    /// Base58-encoded Ed25519 private key
    #[serde(rename = "buyer_private_key")]
    pub buyer_private_key: String,
    #[serde(rename = "payment_cid")]
    pub payment_cid: String,
    /// Amount to add
    #[serde(rename = "amount")]
    pub amount: String,
    /// New expiry time (ISO 8601)
    #[serde(rename = "new_expires", skip_serializing_if = "Option::is_none")]
    pub new_expires: Option<String>,
    #[serde(rename = "amulet_cids")]
    pub amulet_cids: Vec<String>,
}

impl PaymentTopupRequest {
    pub fn new(buyer_party_id: String, buyer_private_key: String, payment_cid: String, amount: String, amulet_cids: Vec<String>) -> PaymentTopupRequest {
        PaymentTopupRequest {
            jwt: None,
            buyer_party_id,
            buyer_private_key,
            payment_cid,
            amount,
            new_expires: None,
            amulet_cids,
        }
    }
}

