/*
 * Advanced Payment Devnet API
 *
 * REST API for Canton Network Advanced Payment operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaymentUnlockRequest {
    /// JWT for Ledger API authentication
    #[serde(rename = "jwt", skip_serializing_if = "Option::is_none")]
    pub jwt: Option<String>,
    /// Buyer party ID
    #[serde(rename = "buyer_party_id")]
    pub buyer_party_id: String,
    /// Base58-encoded Ed25519 private key
    #[serde(rename = "buyer_private_key")]
    pub buyer_private_key: String,
    #[serde(rename = "payment_cid")]
    pub payment_cid: String,
    #[serde(rename = "amount")]
    pub amount: String,
}

impl PaymentUnlockRequest {
    pub fn new(buyer_party_id: String, buyer_private_key: String, payment_cid: String, amount: String) -> PaymentUnlockRequest {
        PaymentUnlockRequest {
            jwt: None,
            buyer_party_id,
            buyer_private_key,
            payment_cid,
            amount,
        }
    }
}

