/*
 * Advanced Payment Devnet API
 *
 * REST API for Canton Network Advanced Payment operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaymentRequestRejectRequest {
    /// JWT for Ledger API authentication
    #[serde(rename = "jwt", skip_serializing_if = "Option::is_none")]
    pub jwt: Option<String>,
    /// Buyer party ID
    #[serde(rename = "buyer_party_id")]
    pub buyer_party_id: String,
    /// Base58-encoded Ed25519 private key
    #[serde(rename = "buyer_private_key")]
    pub buyer_private_key: String,
    #[serde(rename = "request_cid")]
    pub request_cid: String,
    #[serde(rename = "reason", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub reason: Option<Option<String>>,
}

impl PaymentRequestRejectRequest {
    pub fn new(buyer_party_id: String, buyer_private_key: String, request_cid: String) -> PaymentRequestRejectRequest {
        PaymentRequestRejectRequest {
            jwt: None,
            buyer_party_id,
            buyer_private_key,
            request_cid,
            reason: None,
        }
    }
}

