/*
 * Advanced Payment Devnet API
 *
 * REST API for Canton Network Advanced Payment operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaymentWithdrawRequest {
    /// JWT for Ledger API authentication
    #[serde(rename = "jwt", skip_serializing_if = "Option::is_none")]
    pub jwt: Option<String>,
    /// Seller party ID (e.g., \"ext-user-phantom-1::1220...\")
    #[serde(rename = "seller_party_id", skip_serializing_if = "Option::is_none")]
    pub seller_party_id: Option<String>,
    /// Base58-encoded Ed25519 private key
    #[serde(rename = "seller_private_key", skip_serializing_if = "Option::is_none")]
    pub seller_private_key: Option<String>,
    /// Contract ID of AdvancedPayment
    #[serde(rename = "payment_cid")]
    pub payment_cid: String,
    /// Amount to withdraw (in CC)
    #[serde(rename = "amount")]
    pub amount: String,
    /// Withdrawal reason
    #[serde(rename = "reason", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub reason: Option<Option<String>>,
}

impl PaymentWithdrawRequest {
    pub fn new(payment_cid: String, amount: String) -> PaymentWithdrawRequest {
        PaymentWithdrawRequest {
            jwt: None,
            seller_party_id: None,
            seller_private_key: None,
            payment_cid,
            amount,
            reason: None,
        }
    }
}

