/*
 * Advanced Payment Devnet API
 *
 * REST API for Canton Network Advanced Payment operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaymentRequestCreateRequest {
    /// JWT for Ledger API authentication
    #[serde(rename = "jwt", skip_serializing_if = "Option::is_none")]
    pub jwt: Option<String>,
    /// Seller party ID (e.g., \"ext-user-phantom-1::1220...\")
    #[serde(rename = "seller_party_id", skip_serializing_if = "Option::is_none")]
    pub seller_party_id: Option<String>,
    /// Base58-encoded Ed25519 private key
    #[serde(rename = "seller_private_key", skip_serializing_if = "Option::is_none")]
    pub seller_private_key: Option<String>,
    /// Contract ID of AppService
    #[serde(rename = "service_cid")]
    pub service_cid: String,
    /// Party ID of buyer who will fund payment
    #[serde(rename = "buyer_party_id")]
    pub buyer_party_id: String,
    /// Amount to lock (in CC)
    #[serde(rename = "amount")]
    pub amount: String,
    /// Minimum amount to keep locked
    #[serde(rename = "minimum")]
    pub minimum: String,
    /// ISO 8601 expiry time (default 1 day from now)
    #[serde(rename = "expires", skip_serializing_if = "Option::is_none")]
    pub expires: Option<String>,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "reference", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub reference: Option<Option<String>>,
}

impl PaymentRequestCreateRequest {
    pub fn new(service_cid: String, buyer_party_id: String, amount: String, minimum: String) -> PaymentRequestCreateRequest {
        PaymentRequestCreateRequest {
            jwt: None,
            seller_party_id: None,
            seller_private_key: None,
            service_cid,
            buyer_party_id,
            amount,
            minimum,
            expires: None,
            description: None,
            reference: None,
        }
    }
}

