/*
 * Advanced Payment Devnet API
 *
 * REST API for Canton Network Advanced Payment operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PreapprovalTransferRequest {
    /// JWT for Ledger API authentication (optional, falls back to JWT_PROVIDER)
    #[serde(rename = "jwt", skip_serializing_if = "Option::is_none")]
    pub jwt: Option<String>,
    /// Party ID of the sender (external party)
    #[serde(rename = "sender_party_id")]
    pub sender_party_id: String,
    /// Base58-encoded Ed25519 private key of the sender
    #[serde(rename = "sender_private_key")]
    pub sender_private_key: String,
    /// Party ID of the receiver
    #[serde(rename = "receiver_party_id")]
    pub receiver_party_id: String,
    /// Amount to transfer (in CC)
    #[serde(rename = "amount")]
    pub amount: String,
    /// Transfer description/reason
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
}

impl PreapprovalTransferRequest {
    pub fn new(sender_party_id: String, sender_private_key: String, receiver_party_id: String, amount: String) -> PreapprovalTransferRequest {
        PreapprovalTransferRequest {
            jwt: None,
            sender_party_id,
            sender_private_key,
            receiver_party_id,
            amount,
            description: None,
        }
    }
}

