/*
 * Advanced Payment Devnet API
 *
 * REST API for Canton Network Advanced Payment operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PreapprovalRequestRequest {
    /// JWT for Ledger API authentication (optional, falls back to JWT_PROVIDER)
    #[serde(rename = "jwt", skip_serializing_if = "Option::is_none")]
    pub jwt: Option<String>,
    /// External party ID (receiver of the preapproval)
    #[serde(rename = "party_id")]
    pub party_id: String,
    /// Base58-encoded Ed25519 private key for the external party
    #[serde(rename = "private_key")]
    pub private_key: String,
}

impl PreapprovalRequestRequest {
    pub fn new(party_id: String, private_key: String) -> PreapprovalRequestRequest {
        PreapprovalRequestRequest {
            jwt: None,
            party_id,
            private_key,
        }
    }
}

