/*
 * Advanced Payment Devnet API
 *
 * REST API for Canton Network Advanced Payment operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PreapprovalCancelRequest {
    /// JWT for Ledger API authentication
    #[serde(rename = "jwt", skip_serializing_if = "Option::is_none")]
    pub jwt: Option<String>,
    /// Party ID (defaults to PARTY_PROVIDER if not specified)
    #[serde(rename = "party_id", skip_serializing_if = "Option::is_none")]
    pub party_id: Option<String>,
}

impl PreapprovalCancelRequest {
    pub fn new() -> PreapprovalCancelRequest {
        PreapprovalCancelRequest {
            jwt: None,
            party_id: None,
        }
    }
}

