/*
 * Advanced Payment Devnet API
 *
 * REST API for Canton Network Advanced Payment operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PreapprovalAcceptRequest {
    /// JWT for Ledger API authentication (optional, falls back to JWT_PROVIDER)
    #[serde(rename = "jwt", skip_serializing_if = "Option::is_none")]
    pub jwt: Option<String>,
}

impl PreapprovalAcceptRequest {
    pub fn new() -> PreapprovalAcceptRequest {
        PreapprovalAcceptRequest {
            jwt: None,
        }
    }
}

