/*
 * Advanced Payment Devnet API
 *
 * REST API for Canton Network Advanced Payment operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SellerCredentials : All fields optional - falls back to .env if not provided
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SellerCredentials {
    /// JWT for Ledger API authentication
    #[serde(rename = "jwt", skip_serializing_if = "Option::is_none")]
    pub jwt: Option<String>,
    /// Seller party ID (e.g., \"ext-user-phantom-1::1220...\")
    #[serde(rename = "seller_party_id", skip_serializing_if = "Option::is_none")]
    pub seller_party_id: Option<String>,
    /// Base58-encoded Ed25519 private key
    #[serde(rename = "seller_private_key", skip_serializing_if = "Option::is_none")]
    pub seller_private_key: Option<String>,
}

impl SellerCredentials {
    /// All fields optional - falls back to .env if not provided
    pub fn new() -> SellerCredentials {
        SellerCredentials {
            jwt: None,
            seller_party_id: None,
            seller_private_key: None,
        }
    }
}

