/*
 * Advanced Payment Devnet API
 *
 * REST API for Canton Network Advanced Payment operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServiceTerminateRequest {
    #[serde(rename = "jwt", skip_serializing_if = "Option::is_none")]
    pub jwt: Option<String>,
    #[serde(rename = "service_cid")]
    pub service_cid: String,
}

impl ServiceTerminateRequest {
    pub fn new(service_cid: String) -> ServiceTerminateRequest {
        ServiceTerminateRequest {
            jwt: None,
            service_cid,
        }
    }
}

