/*
 * Advanced Payment Devnet API
 *
 * REST API for Canton Network Advanced Payment operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServiceListRequest {
    #[serde(rename = "jwt", skip_serializing_if = "Option::is_none")]
    pub jwt: Option<String>,
    #[serde(rename = "seller_party_id", skip_serializing_if = "Option::is_none")]
    pub seller_party_id: Option<String>,
}

impl ServiceListRequest {
    pub fn new() -> ServiceListRequest {
        ServiceListRequest {
            jwt: None,
            seller_party_id: None,
        }
    }
}

