/*
 * Advanced Payment Devnet API
 *
 * REST API for Canton Network Advanced Payment operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServiceRequestAcceptRequest {
    /// JWT (optional, falls back to .env)
    #[serde(rename = "jwt", skip_serializing_if = "Option::is_none")]
    pub jwt: Option<String>,
    /// Contract ID of AppServiceRequest
    #[serde(rename = "request_cid")]
    pub request_cid: String,
}

impl ServiceRequestAcceptRequest {
    pub fn new(request_cid: String) -> ServiceRequestAcceptRequest {
        ServiceRequestAcceptRequest {
            jwt: None,
            request_cid,
        }
    }
}

