/*
 * Advanced Payment Devnet API
 *
 * REST API for Canton Network Advanced Payment operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServiceRequestCreateRequest {
    /// JWT for Ledger API authentication
    #[serde(rename = "jwt", skip_serializing_if = "Option::is_none")]
    pub jwt: Option<String>,
    /// Seller party ID (e.g., \"ext-user-phantom-1::1220...\")
    #[serde(rename = "seller_party_id", skip_serializing_if = "Option::is_none")]
    pub seller_party_id: Option<String>,
    /// Base58-encoded Ed25519 private key
    #[serde(rename = "seller_private_key", skip_serializing_if = "Option::is_none")]
    pub seller_private_key: Option<String>,
    /// Description of service relationship
    #[serde(rename = "service_description", skip_serializing_if = "Option::is_none")]
    pub service_description: Option<String>,
}

impl ServiceRequestCreateRequest {
    pub fn new() -> ServiceRequestCreateRequest {
        ServiceRequestCreateRequest {
            jwt: None,
            seller_party_id: None,
            seller_private_key: None,
            service_description: None,
        }
    }
}

