/*
 * Advanced Payment Devnet API
 *
 * REST API for Canton Network Advanced Payment operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServiceRequestRejectRequest {
    #[serde(rename = "jwt", skip_serializing_if = "Option::is_none")]
    pub jwt: Option<String>,
    #[serde(rename = "request_cid")]
    pub request_cid: String,
    #[serde(rename = "reason", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub reason: Option<Option<String>>,
}

impl ServiceRequestRejectRequest {
    pub fn new(request_cid: String) -> ServiceRequestRejectRequest {
        ServiceRequestRejectRequest {
            jwt: None,
            request_cid,
            reason: None,
        }
    }
}

