# .cargo/config.toml
[build]
jobs = 16                 # match vCPU count
rustflags = [
  "-Ctarget-cpu=native",
  "-Ccodegen-units=256",
  "-Ctarget-feature=+crt-static",
  "-Crelocation-model=static"
]