[package]
name = "digicert-tsa"
version = "0.1.0"
edition = "2024"

[lib]
name = "digicert_tsa"
path = "src/lib.rs"

[[bin]]
name = "digicert-tsa"
path = "src/main.rs"

[dependencies]
tokio = { version = "1.43.0", features = ["full"] }
anyhow = "1.0.98"
base64 = "0.22"
cmpv2 = { version = "0.2.0", default-features = false }
cms = "0.2.3"
chrono = "0.4"
der = { version = "0.7", features = ["alloc"] }
hex = "0.4"
once_cell = "1.20"
rand = "0.9"
reqwest = { version = "0.12", default-features = false, features = ["blocking","rustls-tls","json"] }
ring = "0.17"
rsa = { version = "0.9", features = ["sha2"] }
serde_json = "1.0.140"
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.10"
spki = { version = "0.7", default-features = false }
x509-parser = "0.16"
x509-tsp = "0.1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
dotenvy = "0.15.7"
sui_sdk = { git = "https://github.com/mystenlabs/sui", package = "sui-sdk"}
fastcrypto = { git = "https://github.com/MystenLabs/fastcrypto", rev = "69d496c71fb37e3d22fe85e5bbfd4256d61422b9" }
bcs = "0.1.4"