[package]
name = "recursion"
version = "0.1.0"
edition = "2021"

[dependencies]
recursion-methods = { path = "methods" }
balance = { path = "../balance" }
balance-core = { path = "../balance/core" }
risc0-zkvm = { version = "2.0.1", features = ["prove"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[features]
default = []
prove = ["risc0-zkvm/prove"]
