[package]
name = "lambda"
version.workspace = true
edition.workspace = true

[[bin]]
name = "bootstrap"
path = "src/main.rs"

[dependencies]
lambda_runtime = "0.14.2"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["macros"] }
anyhow = "1.0"
