/*
 * Calculator API
 *
 * Simple API for mathematical operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateRegistryResponse {
    /// Object ID of the created registry
    #[serde(rename = "registry_id")]
    pub registry_id: String,
    /// Transaction digest from the blockchain
    #[serde(rename = "tx_digest")]
    pub tx_digest: String,
    /// Admin address (sender) of the registry
    #[serde(rename = "admin_address")]
    pub admin_address: String,
}

impl CreateRegistryResponse {
    pub fn new(registry_id: String, tx_digest: String, admin_address: String) -> CreateRegistryResponse {
        CreateRegistryResponse {
            registry_id,
            tx_digest,
            admin_address,
        }
    }
}

