/*
 * Calculator API
 *
 * Simple API for mathematical operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ErrorResponse {
    /// Error code
    #[serde(rename = "error")]
    pub error: String,
    /// Human-readable error message
    #[serde(rename = "message")]
    pub message: String,
}

impl ErrorResponse {
    pub fn new(error: String, message: String) -> ErrorResponse {
        ErrorResponse {
            error,
            message,
        }
    }
}

