/*
 * Calculator API
 *
 * Simple API for mathematical operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MathRequest {
    /// First unsigned 64-bit integer
    #[serde(rename = "a")]
    pub a: i64,
    /// Second unsigned 64-bit integer
    #[serde(rename = "b")]
    pub b: i64,
}

impl MathRequest {
    pub fn new(a: i64, b: i64) -> MathRequest {
        MathRequest {
            a,
            b,
        }
    }
}

