/*
 * Calculator API
 *
 * Simple API for mathematical operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RemoveAppRequest {
    /// Registry object ID
    #[serde(rename = "registry_id")]
    pub registry_id: String,
    #[serde(rename = "chain")]
    pub chain: models::Chain,
    /// App name
    #[serde(rename = "name")]
    pub name: String,
}

impl RemoveAppRequest {
    pub fn new(registry_id: String, chain: models::Chain, name: String) -> RemoveAppRequest {
        RemoveAppRequest {
            registry_id,
            chain,
            name,
        }
    }
}

