# .cargo/config.toml
[build]
jobs = 16                 # match vCPU count
rustflags = [
  "-Ctarget-cpu=native",
  "-Ccodegen-units=16",
  "-Ctarget-feature=+crt-static",
  "-Crelocation-model=static"
]

[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/MystenLabs/fastcrypto?rev=69d496c71fb37e3d22fe85e5bbfd4256d61422b9"]
git = "https://github.com/MystenLabs/fastcrypto"
rev = "69d496c71fb37e3d22fe85e5bbfd4256d61422b9"
replace-with = "vendored-sources"

[source."git+https://github.com/aws/aws-nitro-enclaves-nsm-api.git/?rev=8ec7eac72bbb2097f1058ee32c13e1ff232f13e8"]
git = "https://github.com/aws/aws-nitro-enclaves-nsm-api.git/"
rev = "8ec7eac72bbb2097f1058ee32c13e1ff232f13e8"
replace-with = "vendored-sources"

[source."git+https://github.com/mystenlabs/sui?rev=574e17b5ef3b96146aebcd23f3e8b1d20b14e6ae"]
git = "https://github.com/mystenlabs/sui"
rev = "574e17b5ef3b96146aebcd23f3e8b1d20b14e6ae"
replace-with = "vendored-sources"

[source."git+https://github.com/o1-labs/proof-systems?branch=master"]
git = "https://github.com/o1-labs/proof-systems"
branch = "master"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor/"