[package]
name = "api"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1.0"
tracing = "0.1"
tokio = { version = "1", features = ["full"] }
api_generated = { path = "../api-generated" }
sui = { path = "../sui" }