[package]
name = "attestation"
version = "0.1.0"
edition = "2024"
authors = ["DFST"]
license = "Apache-2.0"

[dependencies]
bincode = "1.3"
ciborium = "0.2.2"
hex = "0.4.3"
once_cell = "1.21.3"
p384 = "0.13.1"
rustls-pemfile = "2.2.0"
serde = "1.0.219"
serde_json = "1.0.133"
x509-parser = { version = "0.17.0", features = ["verify"] }
