[package]
version = "0.1.0"
name = "mina-program"
edition = "2021"

[lib]
name = "mina_lib"
path = "src/lib.rs"

[[bin]]
name = "mina-program"
path = "src/main.rs"

[dependencies]
sp1-zkvm = { version = "5.1.0" }
crypto-bigint = "=0.5.5"

