[package]
name = "rpc"
version = "0.1.0"
edition = "2024"

[dependencies]
sui-rpc = { git = "https://github.com/MystenLabs/sui-rust-sdk.git" }
sui-sdk-types = { git = "https://github.com/MystenLabs/sui-rust-sdk.git" }
anyhow = "1.0"
tokio = { version = "1.0", features = ["full"] }
dotenv = "0.15"
base64ct = { version = "1.6", features = ["std"] }
sui-crypto = { package = "sui-crypto", git = "https://github.com/MystenLabs/sui-rust-sdk.git", features = ["ed25519"] }
sui-transaction-builder = { package = "sui-transaction-builder", git = "https://github.com/MystenLabs/sui-rust-sdk.git" }
serde_json = "1.0.142"
prost-types = "=0.13.5"
bech32 = "0.9"
hex = "0.4.3"
bcs = "0.1"
serde = { version = "1.0", features = ["derive"] }
